;
; File generated by cc65 v 2.19 - Git a861d84
;
	.fopt		compiler,"cc65 v 2.19 - Git a861d84"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_CHROUT
	.import		_PRNTLN
	.import		_PRNL
	.import		_KBINPUT
	.export		_main

.segment	"RODATA"

S0001:
	.byte	$41,$68,$6F,$6A,$20,$7A,$64,$72,$61,$76,$69,$20,$56,$61,$73,$20
	.byte	$50,$36,$35,$20,$61,$20,$74,$65,$73,$74,$20,$6B,$6C,$61,$76,$65
	.byte	$73,$6E,$69,$63,$65,$21,$21,$00
S0002:
	.byte	$54,$65,$64,$20,$6D,$75,$7A,$65,$73,$20,$7A,$61,$63,$69,$74,$20
	.byte	$70,$73,$61,$74,$00

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	lda     #<(S0001)
	ldx     #>(S0001)
	jsr     _PRNTLN
	lda     #<(S0002)
	ldx     #>(S0002)
	jsr     _PRNTLN
	jsr     _PRNL
L0002:	jsr     _KBINPUT
	jsr     _CHROUT
	bra     L0002

.endproc

