;
; File generated by cc65 v 2.19 - Git a861d84
;
	.fopt		compiler,"cc65 v 2.19 - Git a861d84"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_CHROUT
	.import		_PRNTLN
	.import		_PRNL
	.import		_KBINPUT
	.export		_main

.segment	"RODATA"

S0001:
	.byte	"Ahoj zdravi Vas P65 a test klavesnice!!"
S0002:
	.byte	"Ted muzes zacit psat"


.segment	"CODE"
_main:
	lda     #<(S0001)
	ldx     #>(S0001)
	jsr     _PRNTLN
	lda     #<(S0002)
	ldx     #>(S0002)
	jsr     _PRNTLN
	jsr     _PRNL
L0002:	jsr     _KBINPUT
	jsr     _CHROUT
	bra     L0002
